fix(types): use correct import for react in types (#927) - @loginov-rocks
To fix the following:

node_modules/react-redux-firebase/index.d.ts:1:8 - error TS1259: Module '"/Users/danila/Projects/GitHub/Projects/Portfolio/node_modules/@types/react/index"' can only be default-imported using the 'esModuleInterop' flag

1 import React from 'react'
         ~~~~~

  node_modules/@types/react/index.d.ts:64:1
    64 export = React;
       ~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.